# Generated by Django 3.2.8 on 2021-11-06 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='-', max_length=30)),
                ('course_id', models.CharField(default='10100', max_length=6)),
                ('days', models.CharField(default='TBA', max_length=10)),
                ('time', models.CharField(default='TBA', max_length=20)),
                ('location', models.CharField(default='TBA', max_length=20)),
                ('registraion_window', models.DateTimeField(default=register.models.registraion_period)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
