# Generated by Django 3.2.8 on 2021-11-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='-', max_length=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
