# Generated by Django 3.2.9 on 2021-12-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
