# Generated by Django 3.2.9 on 2021-12-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20211203_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
