# Generated by Django 3.2.9 on 2021-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_profile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Teacher_or_Student',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default=False, max_length=7),
        ),
    ]
