# Generated by Django 3.2.9 on 2021-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20211205_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.CharField(default='5', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
