# Generated by Django 3.2.9 on 2021-12-08 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0016_profile_empl_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
                ('date_posted', models.DateTimeField(default=register.models.registraion_period)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
